language: python
python:
  - 3.4
script: make test
notifications:
  email: false
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/conman'
  matrix:
    - DJANGO='django>=1.7,<1.8'
install:
  - psql -c 'CREATE DATABASE conman' -U postgres;
  - pip install -r test_requirements.txt
  - pip install $DJANGO
